CI update bug fix

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -11,18 +11,17 @@ jobs:
         uses: actions/setup-node@v3
         with:
           node-version: '16'
-          cache: 'npm'
-          
+          cache: 'pnpm'
+
       - name: Install pnpm
         run: npm install -g pnpm
 
+      - name: Ensure pnpm lock file
+        run: |
+          test -f pnpm-lock.yaml || echo "pnpm-lock.yaml not found"
+
       - name: Install Dependencies
         run: pnpm install --no-frozen-lockfile
-
-      - name: Verify Node and pnpm versions
-        run: |
-          node -v
-          pnpm -v
 
       - name: Cypress Tests
         uses: cypress-io/github-action@v5
